"""empty message

Revision ID: 52bc29910309
Revises: 95d7f89c44c2
Create Date: 2017-02-07 23:00:50.118835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52bc29910309'
down_revision = '95d7f89c44c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'images', ['filename'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='unique')
    # ### end Alembic commands ###
